### ISSUE TITLE
Installation doesnt work

### ISSUE THREAD

**Issue by ThisisDennis** [patrickjane/hss-server#1]
Please check your installation guide.

pi@ceres:~ $ cd /srv
pi@ceres:/srv $ mkdir hss
pi@ceres:/srv $ sudo mkdir hss ->isnt it line above? 
pi@ceres:/srv $ sudo chown hss:hss hss -> some error like "could'nt find user" or something like that (sorry can't remember exactly)

**Comment by patrickjane** [comment]
Hi, thanks for the hint, fixed the instructions.

**Comment by ThisisDennis** [comment]
Thanks, maybe i can contribute some skills soon.

**Comment by patrickjane** [comment]
Good to hear, hope youre happy with the platform.

One thing to note about the skill-registry: since its running on a free tier heroku account, it will power down after a certain idle time, so the first access will take some seconds (e.g. registering skills, querying skills etc.). 

Since there is not too much interest for my hss-skill platform, I havent developed this any further in terms of better hosting / more user friendly connection.
